"""
Evaluate MoD-aware line selection on hold-out instances.

For each test instance directory (with config.yaml / demand / dm like the main pipeline):

- baseline/: first-iteration behavior — initial preprocessing MoD costs, one ILP solve, one DARP run.
- proposed/: same pipeline but MoD coefficients are calibrated from a *completed* MoD-aware
  results folder (``iteration_1`` … ``iteration_K``) on a *reference* instance.

Transfer uses **exported MoD cost CSVs** from a completed reference run (no replay):

- ``mod_costs_initial.csv`` at the reference results root (pre-first-iteration coefficients).
- ``mod_cost_snapshot.csv`` in the **last** ``iteration_<n>`` folder (coefficients after that
  iteration's ``update_mod_costs``).

**Scale** mode: mean ratio of (final / initial) total MoD leg cost per trip option, matching any
recompute strategy. **Copy** mode: copies ``first_mile_cost``, ``last_mile_cost``, ``mt_cost`` from
the final CSV onto matching (passenger, route) options on the test instance.

Reference results directory must contain ``experiment.yaml`` (``instance:`` ...) and the CSV
files above (generated by ``MoD-aware_line_selection.py``).
"""

from __future__ import annotations

import argparse
import importlib.util
import json
import logging
import re
import sys
import time
from pathlib import Path
from typing import Any, Dict, List, Tuple

import darpbenchmark.experiments
import darpinstances.inout

import lineplanning.instance
import lineplanning.instance_config
import lineplanning.line_planning

_REPO_ROOT = Path(__file__).resolve().parent.parent
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))


def _load_mod_aware_module():
    path = Path(__file__).resolve().parent / "MoD-aware_line_selection.py"
    spec = importlib.util.spec_from_file_location("mod_aware_line_selection", path)
    if spec is None or spec.loader is None:
        raise ImportError(f"Cannot load spec for {path}")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def _find_experiment_yaml_in_results(reference_results_dir: Path) -> Path:
    d = reference_results_dir.resolve()
    for name in ("experiment.yaml", "experiment.yml"):
        p = d / name
        if p.is_file():
            return p
    raise FileNotFoundError(
        f"Expected experiment.yaml or experiment.yml in {d} "
        "(with key 'instance' pointing to the reference instance config)."
    )


def reference_paths_from_results(reference_results_dir: Path) -> Tuple[Path, Path]:
    """
    Resolve paths from experiment YAML co-located with MoD-aware results.

    Returns:
        (experiment_yaml_path, instance_config_path) with ``instance_config_path`` as in
        ``resolve_instance_config_path`` (the line-planning instance config YAML).
    """
    exp_path = _find_experiment_yaml_in_results(reference_results_dir)
    experiment = lineplanning.instance_config.load_experiment_yaml(exp_path)
    inst_cfg = lineplanning.instance_config.resolve_instance_config_path(exp_path, experiment)
    return exp_path, inst_cfg.resolve()


def _list_iteration_dirs(results_root: Path) -> List[Path]:
    numbered: List[Tuple[int, Path]] = []
    for p in results_root.iterdir():
        if not p.is_dir():
            continue
        m = re.fullmatch(r"iteration_(\d+)", p.name)
        if m:
            numbered.append((int(m.group(1)), p))
    return [path for _, path in sorted(numbered)]


def _mod_cost_rows_to_totals_index(rows: List[Dict[str, Any]]) -> Dict[Tuple, float]:
    """Per-option MoD leg totals for scale calibration: (\"d\", p) and (\"l\", p, rho)."""
    out: Dict[Tuple, float] = {}
    for row in rows:
        p = int(row["passenger_idx"])
        rho = int(row["line_idx"])
        fm = float(row["first_mile_cost"])
        lm = float(row["last_mile_cost"])
        if rho < 0:
            out[("d", p)] = fm + lm
        else:
            out[("l", p, rho)] = fm + lm
    return out


def _mean_cost_scale_factor(initial: Dict[Tuple, float], final: Dict[Tuple, float]) -> float:
    ratios: List[float] = []
    for key, v0 in initial.items():
        if key not in final:
            continue
        v1 = final[key]
        if v0 > 1e-12:
            ratios.append(v1 / v0)
    if not ratios:
        logging.warning("No valid cost ratios; using scale factor 1.0")
        return 1.0
    return float(sum(ratios) / len(ratios))


def load_reference_calibration_from_snapshots(
    reference_results_dir: Path,
    mod: Any,
) -> Tuple[float, List[Dict[str, Any]]]:
    """
    Load initial and final MoD cost CSVs from a completed MoD-aware run.
    Returns (mean scale factor initial→final, final CSV rows for copy mode).
    """
    root = Path(reference_results_dir).resolve()
    initial_path = root / mod.MOD_COST_INITIAL_FILENAME
    if not initial_path.is_file():
        raise FileNotFoundError(
            f"Missing {mod.MOD_COST_INITIAL_FILENAME} under {root}. "
            "Re-run MoD-aware_line_selection.py to export MoD cost CSVs."
        )
    iteration_dirs = _list_iteration_dirs(root)
    if not iteration_dirs:
        raise FileNotFoundError(f"No iteration_* subdirectories under {root}")
    last_dir = iteration_dirs[-1]
    final_path = last_dir / mod.MOD_COST_SNAPSHOT_FILENAME
    if not final_path.is_file():
        raise FileNotFoundError(
            f"Missing {mod.MOD_COST_SNAPSHOT_FILENAME} in {last_dir}. "
            "Re-run MoD-aware_line_selection.py to export MoD cost CSVs."
        )
    initial_rows = mod.read_mod_costs_csv(initial_path)
    final_rows = mod.read_mod_costs_csv(final_path)
    init_idx = _mod_cost_rows_to_totals_index(initial_rows)
    fin_idx = _mod_cost_rows_to_totals_index(final_rows)
    factor = _mean_cost_scale_factor(init_idx, fin_idx)
    logging.info(
        "Reference calibration from MoD cost CSVs (%s → %s): mean MoD cost scale = %s",
        initial_path.name,
        last_dir.name,
        factor,
    )
    return factor, final_rows


def _darp_total_plan_cost(solution_path: Path) -> float:
    sol = darpinstances.inout.load_json(solution_path)
    return float(sum(float(p["cost"]) for p in sol["plans"]))


def _setup_run_logging(log_path: Path) -> logging.Handler:
    log_path.parent.mkdir(parents=True, exist_ok=True)
    root = logging.getLogger()
    fh = logging.FileHandler(log_path, mode="w", encoding="utf-8")
    fh.setLevel(logging.DEBUG)
    fh.setFormatter(
        logging.Formatter("%(asctime)s.%(msecs)03d %(levelname)s %(name)s: %(message)s")
    )
    root.addHandler(fh)
    return fh


def run_first_iteration_pipeline(
    mod: Any,
    instance_dir: Path,
    output_dir: Path,
    *,
    calibration: str,
    calibration_scale: float | None = None,
    reference_mod_cost_rows: List[Dict[str, Any]] | None = None,
) -> Dict[str, Any]:
    """
    One ILP + one DARP, matching the first iteration of MoD-aware_line_selection.py
    (optional calibration of MoD costs before the ILP).
    """
    output_dir.mkdir(parents=True, exist_ok=True)
    demand_file, dm_file = mod._load_demand_and_dm_from_instance_config(instance_dir)
    candidate_lines_file = instance_dir / "lines.txt"

    line_inst = lineplanning.instance.line_instance(
        candidate_lines_file=candidate_lines_file,
        capacity=30,
        maximum_detour=3,
        demand_file=demand_file,
        preprocessing_dir=instance_dir / "preprocessing",
        dm_file=dm_file,
    )

    if calibration == "none":
        pass
    elif calibration == "scale":
        if calibration_scale is None:
            raise ValueError("calibration='scale' requires calibration_scale")
        if abs(calibration_scale - 1.0) > 1e-15:
            mod._scale_all_mod_costs_in_model(line_inst, calibration_scale)
    elif calibration == "copy":
        if reference_mod_cost_rows is None:
            raise ValueError("calibration='copy' requires reference_mod_cost_rows")
        mod.apply_mod_cost_rows_to_instance(line_inst, reference_mod_cost_rows)
    else:
        raise ValueError(f"Unknown calibration mode {calibration!r}")

    solver = lineplanning.line_planning.LinePlanningSolver(
        line_inst,
        time_limit=mod.line_planning_ILP_time_limit,
        cost_coefficient=1.0,
        max_frequency=mod.max_frequency,
    )

    instance_size_label = lineplanning.line_planning.get_instance_size_label(str(demand_file))

    results_dir_path_per_iteration = output_dir
    results_dir_path_per_iteration.mkdir(parents=True, exist_ok=True)

    obj_val, run_time_ILP, selected_lines, request_assignments, line_cost, mod_cost = (
        solver.solve_MoD_aware_ILP(
            export_model=True,
            export_solution=True,
            output_dir=results_dir_path_per_iteration,
            gurobi_log_file=results_dir_path_per_iteration / "gurobi.log",
            max_route_frequency=mod.max_frequency,
            rejection_cost=mod.rejection_cost,
            use_request_line_valid_inequalities=True,
            reuse_model=False,
        )
    )

    darp_requests = mod.solution_to_darp_requests(
        line_inst,
        request_assignments,
        request_times=None,
        delta_transfer_seconds=0,
    )
    requests_csv_path = results_dir_path_per_iteration / "requests.csv"
    mod.write_darp_requests_csv(darp_requests, requests_csv_path, time_format="seconds")
    mod.write_darp_vehicles_csv(
        darp_requests,
        results_dir_path_per_iteration / "vehicles.csv",
        capacity=5,
        time_format="seconds",
    )
    mod.write_darp_config_yaml(
        output_dir=results_dir_path_per_iteration,
        dm_filepath=dm_file,
        max_travel_time_delay_seconds=300,
        vehicle_capacity=5,
    )

    experiment_config_path = results_dir_path_per_iteration / "experiment_ih.yaml"
    darpbenchmark.experiments.run_experiment_using_config(
        experiment_config_path,
        executable_path=mod.DARP_BENCHMARK_PATH,
    )

    solution_path = results_dir_path_per_iteration / "config.yaml-solution.json"
    darp_objective = _darp_total_plan_cost(solution_path)

    metrics = {
        "objective_value": obj_val,
        "line_cost": line_cost,
        "mod_cost": mod_cost,
        "run_time_seconds": run_time_ILP,
        "instance_size": instance_size_label,
        "demand_file": str(demand_file),
        "dm_file": str(dm_file),
        "max_route_frequency": mod.max_frequency,
        "calibration": calibration,
        "calibration_scale": calibration_scale,
        "timestamp": time.strftime("%Y-%m-%dT%H:%M:%S"),
        "darp_total_plan_cost_sum": darp_objective,
    }
    (results_dir_path_per_iteration / "metrics.json").write_text(
        json.dumps(metrics, indent=2),
        encoding="utf-8",
    )
    return metrics


def _instance_subdir_name(instance_path: Path) -> str:
    name = instance_path.name
    if not name or name in (".", ".."):
        return instance_path.resolve().name
    return name


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--work-dir",
        type=Path,
        required=True,
        help="Output root: <work-dir>/<instance-name>/{baseline,proposed}/",
    )
    parser.add_argument(
        "--reference-results-dir",
        type=Path,
        required=True,
        help=(
            "MoD-aware results root: contains experiment.yaml (instance: ...) and iteration_1, ..."
        ),
    )
    parser.add_argument(
        "--mod-cost-mode",
        choices=("scale", "copy"),
        default="scale",
        help="How to transfer replayed reference MoD costs to test instances (default: scale).",
    )
    parser.add_argument(
        "--instance-dirs",
        nargs="+",
        type=Path,
        help="Test instance directories (each with config.yaml and lines.txt).",
    )
    args = parser.parse_args()

    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s.%(msecs)03d %(levelname)s %(name)s: %(message)s",
        datefmt="%Y-%m-%d %H:%M:%S",
    )

    mod = _load_mod_aware_module()

    work_dir = args.work_dir.resolve()
    work_dir.mkdir(parents=True, exist_ok=True)

    ref_results = args.reference_results_dir.resolve()
    ref_experiment_yaml, ref_instance_config = reference_paths_from_results(ref_results)
    ref_instance_dir = ref_instance_config.parent.resolve()

    scale_factor, ref_final_rows = load_reference_calibration_from_snapshots(
        ref_results,
        mod,
    )

    summary: Dict[str, Any] = {
        "reference_results_dir": str(ref_results),
        "reference_experiment_yaml": str(ref_experiment_yaml),
        "reference_instance_config": str(ref_instance_config),
        "reference_instance_dir": str(ref_instance_dir),
        "mean_mod_cost_scale_factor": scale_factor,
        "mod_cost_mode": args.mod_cost_mode,
        "reference_calibration": "mod_cost_csv",
        "instances": {},
    }

    for inst_path in args.instance_dirs:
        inst_path = inst_path.resolve()
        sub = _instance_subdir_name(inst_path)
        base_out = work_dir / sub / "baseline"
        prop_out = work_dir / sub / "proposed"

        fh_base = _setup_run_logging(base_out / "run.log")
        logging.info("Baseline run: %s -> %s", inst_path, base_out)
        try:
            b_metrics = run_first_iteration_pipeline(
                mod,
                inst_path,
                base_out,
                calibration="none",
            )
        finally:
            logging.getLogger().removeHandler(fh_base)
            fh_base.close()

        fh_prop = _setup_run_logging(prop_out / "run.log")
        logging.info("Proposed run: %s -> %s", inst_path, prop_out)
        try:
            if args.mod_cost_mode == "scale":
                p_metrics = run_first_iteration_pipeline(
                    mod,
                    inst_path,
                    prop_out,
                    calibration="scale",
                    calibration_scale=scale_factor,
                )
            else:
                p_metrics = run_first_iteration_pipeline(
                    mod,
                    inst_path,
                    prop_out,
                    calibration="copy",
                    reference_mod_cost_rows=ref_final_rows,
                )
        finally:
            logging.getLogger().removeHandler(fh_prop)
            fh_prop.close()

        summary["instances"][sub] = {
            "instance_dir": str(inst_path),
            "baseline": b_metrics,
            "proposed": p_metrics,
        }

    summary_path = work_dir / "summary.json"
    summary_path.write_text(json.dumps(summary, indent=2), encoding="utf-8")
    logging.info("Wrote %s", summary_path)


if __name__ == "__main__":
    main()
